name: Build EaglercraftX 1.8.8 Custom Client

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # 3. Build standalone client
      - name: Build Standalone Client
        run: |
          cd buildtools
          java -jar BuildTools.jar --makeStandaloneClient
          cd ..

      # 4. Upload built files
      - name: Upload Standalone Build
        uses: actions/upload-artifact@v4
        with:
          name: EaglercraftX-Standalone
          path: buildtools/latest-client/**
          if-no-files-found: error
