name: Build EaglercraftX 1.8.8 Standalone

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java 17 (required for BuildTools)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build standalone HTML client
      - name: Build standalone client
        run: |
          cd buildtools
          java -jar BuildTools.jar --make latest-client --teavm --offline

      # 4. Upload built files as artifact
      - name: Upload standalone client
        uses: actions/upload-artifact@v4
        with:
          name: eaglercraftx-standalone
          path: buildtools/latest-client/**
