name: Build EaglercraftX 1.8.8 Custom Client

on:
  workflow_dispatch:  # Allows you to manually trigger builds
  push:              # Also builds when you push changes
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Java 17 (TeaVM + BuildTools require Java 17)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # 3. Run BuildTools to create standalone HTML
      - name: Build Standalone Client
        run: |
          cd buildtools
          java -jar BuildTools.jar --makeStandalone
          cd ..

      # 4. Upload the compiled HTML as an artifact
      - name: Upload Standalone Build
        uses: actions/upload-artifact@v3
        with:
          name: EaglercraftX-Standalone
          path: buildtools/output/*
