name: Build EaglercraftX HTML

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zip unzip

      - name: Compile Java files
        run: |
          mkdir -p build/classes
          javac -d build/classes $(find src -name "*.java")

      - name: Package into JAR
        run: |
          mkdir -p build/jar
          jar --create --file build/jar/eaglercraft.jar -C build/classes .

      - name: Build standalone HTML
        run: |
          mkdir -p build/output
          cp web/index.html build/output/index.html
          cp web/* build/output/ || true
          cp build/jar/eaglercraft.jar build/output/eaglercraft.jar

      - name: Upload final build
        uses: actions/upload-artifact@v4
        with:
          name: eaglercraft-standalone
          path: build/output
